repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: .txt$
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
    - id: pyupgrade
      args: [--py37-plus]
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
    - id: black
    - id: black-jupyter
- repo: https://github.com/PyCQA/pylint
  rev: v2.16.0b1
  hooks:
    - id: pylint
      args: [--rcfile=.pylintrc]
      files: ^gEconpy/
- repo: local
  hooks:
    - id: no-relative-imports
      name: No relative imports
      entry: from \.[\.\w]* import
      types: [python]
      language: pygrep
